#= config.yaml

BINARIZATION_WEIGHT: 1.0
CLASSIFICATION_WEIGHT: 1.0
DATASET_PATH: "./dataset/"
DRY_RUN: false
GALLERY_PATH: "./gallery/"
GNN_LAYER_DIMENSIONS: [128, 256, 128]
HEAD_LAYER_DIMENSIONS: [64]
INVERTED_TETRAHEDRA_WEIGHT: 0.1
LOG_PATH: "runs.json"
LR: 0.00005
MAX_DATASET_SIZE: null
MAX_EPOCHS: 50
MAX_THICKENING: 10.0
PATIENCE: 10
REGRESSION_WEIGHT: 1.0
SEED: 37
THICKENING_THRESHOLD: 0.5
TRAIN_VAL_TEST_RATIO: [0.85, 0.1, 0.05]
WEIGHTS_PATH: "./weights/"