#= config.yaml

BINARIZATION_WEIGHT: 1.0
CLASSIFICATION_WEIGHT: 1.0
DATASET_PATH: "./dataset/"
DRY_RUN: false
GNN_LAYER_DIMENSIONS: [128, 256, 128]
HEAD_LAYER_DIMENSIONS: [64]
INVERTED_TETRAHEDRA_WEIGHT: 0.1
LEARNING_RATE: 0.0001
LOG_PATH: "runs.json"
MAX_DATASET_SIZE: null
MAX_EPOCHS: 50
MAX_THICKENING: 10.0
PATIENCE: 10
REGRESSION_WEIGHT: 1.0
RUNS_PATH: "./runs/"
SEED: 37
THICKENING_THRESHOLD: 0.5
TRAIN_VAL_TEST_RATIO: [0.8, 0.15, 0.05]